services:
  - type: web
    name: kamlesh-temani-app
    env: node
    buildCommand: |
      npm install
      npm run build   # builds React into /dist
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT       # Render assigns a port dynamically
        value: 10000    # placeholder (Render will override)
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GOOGLE_PLACES_API_KEY
        sync: false
      - key: GOOGLE_PLACE_ID
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: COUNSELOR_EMAIL
        sync: false
      - key: COUNSELOR_PHONE
        sync: false
      - key: COUNSELOR_NAME
        sync: false
